# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 520)
        self.index = QtWidgets.QLineEdit(Form)
        self.index.setGeometry(QtCore.QRect(30, 20, 240, 50))
        self.index.setObjectName("index")
        self.resistance = QtWidgets.QLineEdit(Form)
        self.resistance.setGeometry(QtCore.QRect(570, 20, 240, 50))
        self.resistance.setMaxLength(4)
        self.resistance.setObjectName("resistance")
        self.volume = QtWidgets.QLineEdit(Form)
        self.volume.setGeometry(QtCore.QRect(300, 20, 240, 50))
        self.volume.setMaxLength(4)
        self.volume.setObjectName("volume")
        self.btn_next = QtWidgets.QPushButton(Form)
        self.btn_next.setGeometry(QtCore.QRect(830, 20, 60, 50))
        self.btn_next.setObjectName("btn_next")
        self.btn_export = QtWidgets.QPushButton(Form)
        self.btn_export.setGeometry(QtCore.QRect(910, 20, 60, 50))
        self.btn_export.setObjectName("btn_export")
        self.output = QtWidgets.QLabel(Form)
        self.output.setGeometry(QtCore.QRect(30, 90, 65536, 50))
        self.output.setText("")
        self.output.setObjectName("output")
        self.historyTable = QtWidgets.QTableWidget(Form)
        self.historyTable.setGeometry(QtCore.QRect(30, 160, 940, 340))
        self.historyTable.setObjectName("historyTable")
        self.historyTable.setColumnCount(4)
        self.historyTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.historyTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyTable.setHorizontalHeaderItem(3, item)
        self.historyTable.verticalHeader().setVisible(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QRCodegen"))
        self.index.setPlaceholderText(_translate("Form", "序列号"))
        self.resistance.setPlaceholderText(_translate("Form", "线圈阻值(Ω)"))
        self.volume.setPlaceholderText(_translate("Form", "流量(L/min)"))
        self.btn_next.setText(_translate("Form", "下一条"))
        self.btn_export.setText(_translate("Form", "导出"))
        item = self.historyTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.historyTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "VOL"))
        item = self.historyTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "RES"))
        item = self.historyTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "CGEN"))
